# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: EBGN594 HW
author: Jared Andreatta
logo: mines.jpg

execute:
  execute_notebooks: force
  hide_code_input: false

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/jaredandreatta/TimeSeriesJupyterBook
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  baseurl: ""
  title: "Time Series Econometrics"
  
  # Add custom CSS file
  extra_css:
    - _build/html/_static/basic.css  # Path to your CSS file

sphinx:
  config:
    myst_enable_extensions: ["dollarmath", "amsmath", "deflist", "colon_fence", "html_admonition", "html_image", "replacements", "smartquotes", "substitution", "tasklist"]
    html_theme_options:
      togglebutton:
        code: true
